### ISSUE TITLE
broken make serve in template app

### ISSUE THREAD

**Issue by fvanderbiest** [camptocamp/c2cgeoform#125]
```
.build/venv/bin/pserve --reload development.ini
Starting monitor for PID 12087.
2017-11-03 13:10:21,609 INFO  [shapely.speedups._speedups][MainThread] Numpy was not imported, continuing without requires()
Traceback (most recent call last):
  File "/home/fvanderbiest/workspace/MyGeoformProject/.build/venv/lib/python3.5/site-packages/pyramid/config/__init__.py", line 1212, in execute_actions
    callable(*args, **kw)
  File "/home/fvanderbiest/workspace/MyGeoformProject/.build/venv/lib/python3.5/site-packages/pyramid/config/assets.py", line 381, in register
    __import__(package)
ImportError: No module named 'c2cgeoform_demo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/fvanderbiest/workspace/MyGeoformProject/.build/venv/lib/python3.5/site-packages/hupper/ipc.py", line 322, in spawn_main
    func(**kwargs)
  File "/home/fvanderbiest/workspace/MyGeoformProject/.build/venv/lib/python3.5/site-packages/hupper/worker.py", line 237, in worker_main
    func(*spec_args, **spec_kwargs)
  File "/home/fvanderbiest/workspace/MyGeoformProject/.build/venv/lib/python3.5/site-packages/pyramid/scripts/pserve.py", line 32, in main
    return command.run()
  File "/home/fvanderbiest/workspace/MyGeoformProject/.build/venv/lib/python3.5/site-packages/pyramid/scripts/pserve.py", line 229, in run
    app = loader.get_wsgi_app(app_name, config_vars)
  File "/home/fvanderbiest/workspace/MyGeoformProject/.build/venv/lib/python3.5/site-packages/plaster_pastedeploy/__init__.py", line 131, in get_wsgi_app
    global_conf=defaults)
  File "/home/fvanderbiest/workspace/MyGeoformProject/.build/venv/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/fvanderbiest/workspace/MyGeoformProject/.build/venv/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/home/fvanderbiest/workspace/MyGeoformProject/.build/venv/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/fvanderbiest/workspace/MyGeoformProject/.build/venv/lib/python3.5/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/fvanderbiest/workspace/MyGeoformProject/.build/venv/lib/python3.5/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/fvanderbiest/workspace/MyGeoformProject/mygeoformproject/__init__.py", line 31, in main
    return config.make_wsgi_app()
  File "/home/fvanderbiest/workspace/MyGeoformProject/.build/venv/lib/python3.5/site-packages/pyramid/config/__init__.py", line 1052, in make_wsgi_app
    self.commit()
  File "/home/fvanderbiest/workspace/MyGeoformProject/.build/venv/lib/python3.5/site-packages/pyramid/config/__init__.py", line 684, in commit
    self.action_state.execute_actions(introspector=self.introspector)
  File "/home/fvanderbiest/workspace/MyGeoformProject/.build/venv/lib/python3.5/site-packages/pyramid/config/__init__.py", line 1218, in execute_actions
    tb)
  File "/home/fvanderbiest/workspace/MyGeoformProject/.build/venv/lib/python3.5/site-packages/pyramid/compat.py", line 147, in reraise
    raise value.with_traceback(tb)
  File "/home/fvanderbiest/workspace/MyGeoformProject/.build/venv/lib/python3.5/site-packages/pyramid/config/__init__.py", line 1212, in execute_actions
    callable(*args, **kw)
  File "/home/fvanderbiest/workspace/MyGeoformProject/.build/venv/lib/python3.5/site-packages/pyramid/config/assets.py", line 381, in register
    __import__(package)
pyramid.exceptions.ConfigurationExecutionError: <class 'ImportError'>: No module named 'c2cgeoform_demo'
  in:
  Line 16 of file /home/fvanderbiest/workspace/MyGeoformProject/mygeoformproject/routes.py:
    'node_modules'))
```

**Comment by arnaud-morvan** [comment]
Works now
