### ISSUE TITLE
404 not found on comments page (scaffolded app)

### ISSUE THREAD

**Issue by fvanderbiest** [camptocamp/c2cgeoform#127]
```
2017-11-03 14:08:00,240 ERROR [pyramid_debugtoolbar][waitress] Squashed Exception at http://localhost:6543/comments/
traceback url: http://localhost:6543/_debug_toolbar/313430303732313739393934373532/exception
Traceback (most recent call last):
  File "/home/fvanderbiest/workspace/MyProject/.build/venv/lib/python3.5/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/home/fvanderbiest/workspace/MyProject/.build/venv/lib/python3.5/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/home/fvanderbiest/workspace/MyProject/.build/venv/lib/python3.5/site-packages/pyramid/view.py", line 648, in _call_view
    raise pme
  File "/home/fvanderbiest/workspace/MyProject/.build/venv/lib/python3.5/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/home/fvanderbiest/workspace/MyProject/.build/venv/lib/python3.5/site-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "/home/fvanderbiest/workspace/MyProject/.build/venv/lib/python3.5/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    view_name, predicate.text()))
pyramid.exceptions.PredicateMismatch: predicate mismatch for view ExcavationViews (match_param table=excavations)
```

**Comment by arnaud-morvan** [comment]
Comments link have been removed from the navigation bar.
